### ISSUE TITLE
State Abbreviations to Geo_Data

### ISSUE THREAD

**Issue by SerenityUX** [hackclub/clubsdirectory#9]
I think most countries put their state equivalent in the name of the address, but in the US we use abbreviations. @Arpan-206, on the API-side could you test for these abbreviations and set the us_state inside geo_data as that state?
Here's what that code may look like:
https://pastebin.com/smRiESKM

**Comment by Arpan-206** [comment]
Done in commit f9b3c511e592c79867abf26d1905b02d486a312c.
